const SHOW_INFO_MESSAGE = 'SHOW_INFO_MESSAGE';
const SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';
const SHOW_SUCCESS_MESSAGE = 'SHOW_SUCCESS_MESSAGE';

const actions = { SHOW_INFO_MESSAGE, SHOW_ERROR_MESSAGE, SHOW_SUCCESS_MESSAGE };
export default actions;